// Single eslint config for the whole monorepo. Rules that are genuinely global
// live at the top; the browser/React-specific block is scoped to packages/web so
// the API and shared packages never pick up DOM globals or React rules.
//
// eslint-config-prettier goes last in every `extends` chain: Prettier is the
// formatting authority, so stylistic rules that would fight it are switched off
// rather than hand-satisfied.

import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  globalIgnores([
    "**/dist/**",
    "**/dist-cjs/**",
    "**/coverage/**",
    "**/node_modules/**",
  ]),

  // API and shared: Node, no DOM.
  {
    files: ["packages/api/**/*.ts", "packages/shared/**/*.ts"],
    extends: [js.configs.recommended, tseslint.configs.recommended, prettier],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.node,
    },
    rules: {
      // The models layer builds SQL from typed row shapes that pg returns as
      // any; forbidding it outright would mean asserting types we cannot prove.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // `const { password_hash, ...rest } = user` is how fields are omitted;
          // the named sibling is the point, not an oversight.
          ignoreRestSiblings: true,
        },
      ],
      // console is reserved for the email console provider and the CLI scripts,
      // which are exempted below; everything else uses utils/logger.
      "no-console": "error",
      // Transaction control belongs to withTransaction, which cannot forget the
      // release or the rollback. Enforced rather than merely documented.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.property.name='query'] > Literal[value=/^\\s*(BEGIN|COMMIT|ROLLBACK)/i]",
          message:
            "Use withTransaction (utils/withTransaction.ts) instead of hand-rolling BEGIN/COMMIT/ROLLBACK.",
        },
      ],
    },
  },

  // The two places transaction control legitimately lives: the wrapper itself,
  // and the migration runner, which needs one transaction per migration file.
  {
    files: [
      "packages/api/src/utils/withTransaction.ts",
      "packages/api/src/database/migrate.ts",
    ],
    rules: {
      "no-restricted-syntax": "off",
    },
  },

  // Printing to the console is the whole job of these files.
  {
    files: [
      "packages/api/src/utils/email/providers/ConsoleEmailProvider.ts",
      "packages/api/setup.ts",
      "packages/api/run-seed.ts",
      "packages/api/run-migrate.ts",
      "packages/api/src/database/seed.ts",
      "packages/api/src/database/migrate.ts",
    ],
    rules: {
      "no-console": "off",
    },
  },

  // Jest globals for the API suites.
  {
    files: ["packages/api/__tests__/**/*.ts", "packages/api/jest.*.ts"],
    languageOptions: {
      globals: { ...globals.node, ...globals.jest },
    },
    rules: {
      // `require` after a `jest.mock(...)` call is the only way to reach the
      // mocked binding — a static import is hoisted above the mock and would
      // capture the real module instead.
      "@typescript-eslint/no-require-imports": "off",
      // The CRUD suites drive BEGIN/ROLLBACK themselves to prove model functions
      // honour an injected client, and to leave the test DB untouched. That is
      // the assertion, not a transaction to be wrapped.
      "no-restricted-syntax": "off",
    },
  },

  // Web: browser globals plus the React rules.
  {
    files: ["packages/web/**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      prettier,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // `const { password_hash, ...rest } = user` is how fields are omitted;
          // the named sibling is the point, not an oversight.
          ignoreRestSiblings: true,
        },
      ],
      // A hot-reload ergonomics hint, not a correctness rule. The shadcn
      // primitives in components/ui export their variant helpers alongside the
      // component and are regenerated by `npx shadcn add`, so it cannot be
      // satisfied there without hand-editing generated files.
      "react-refresh/only-export-components": "warn",
    },
  },
]);
